package com.campus.api.resources;
import com.campus.api.models.SensorData;
import com.campus.api.store.DataStorage;
import com.campus.api.exceptions.SensorUnavailableException;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import java.util.ArrayList;
import java.util.UUID;
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class SensorReading {
    private String sensorId;
    public SensorReading(String sensorId) { this.sensorId = sensorId; }
    @GET
    public Response getReadings() {
        SensorData sensor = DataStorage.sensors.get(sensorId);
        if (sensor == null) return Response.status(Response.Status.NOT_FOUND).entity("{\"error\":\"Sensor not found\"}").build();
        if (sensor.getReadings() == null || sensor.getReadings().isEmpty()) return Response.ok(new java.util.ArrayList<>()).build();
        return Response.ok(sensor.getReadings()).build();
    }
    @POST
    public Response addReading(com.campus.api.models.SensorReading reading) {
        SensorData sensor = DataStorage.sensors.get(sensorId);
        if (sensor == null) return Response.status(Response.Status.NOT_FOUND).entity("{\"error\":\"Sensor not found\"}").build();
        if (reading == null) {
            return Response.status(Response.Status.BAD_REQUEST)
                    .entity("{\"error\":\"Reading payload is required\"}")
                    .build();
        }
        if ("MAINTENANCE".equalsIgnoreCase(sensor.getStatus())) {
            throw new SensorUnavailableException("Sensor " + sensorId + " is currently in maintenance.");
        }
        if (sensor.getReadings() == null) {
            sensor.setReadings(new ArrayList<>());
        }
        // ID is always generated by server; client does not need to send it.
        reading.setId(UUID.randomUUID().toString());
        if (reading.getTimestamp() == 0) reading.setTimestamp(System.currentTimeMillis());
        sensor.getReadings().add(reading);
        sensor.setCurrentValue(reading.getValue());
        return Response.status(Response.Status.CREATED)
                .entity(java.util.Map.of("message", "Sensor reading added successfully", "reading", reading))
                .build();
    }
}